### ISSUE TITLE
Refactor `.travis.yml`

### ISSUE THREAD

**Issue by sobolevn** [sobolevn/dump-env#7]
We use Travis CI to test our code. We define all the configuration for this tool in this file: https://github.com/sobolevn/dump-env/blob/master/.travis.yml

Currently it still uses `tox` and `setup.py` files to run tests.
We need to switch to `poetry`.

Things to do: 
1. remove `setup.py`
2. remove `tox.ini`
3. add `pyhon3.5` to the supported versions here: https://github.com/sobolevn/dump-env/blob/master/pyproject.toml#L35
4. run `poetry lock` to create `pyproject.lock` file
5. refactor `travis.yml`, example: https://github.com/sobolevn/jinja2-git/blob/master/.travis.yml

@tmsv please ask any questions you have

**Comment by tmsv** [comment]
@sobolevn hi there. I'm trying to create the `pyproject.lock` file. But it leads to error:
```
[VenvCommandError]
Command ['C:\\Users\\hpprobook\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\dump-env-py3.6\\Scripts\\pip.exe', 'freeze'] errored with the following output:
                                                                                                                        
lock
```

I tried to find the solution in google. But I didn't find the relevant info despite I tried different search queries. I do not understand the reason for the error. Can you provide any help please?

**Comment by sobolevn** [comment]
@tmsv sorry, I am a windows user. You can fire a bug here: https://github.com/sdispater/poetry

**Comment by tmsv** [comment]
@sobolevn hi there!
I handled `[VenvCommandError]` by creating new `pyproject.toml` from the beginning on the other computer.
Then I used `poetry install` to create `pyproject.lock`.
I also used `poetry add --dev DEPENDANCY_NAME` to update both `pyproject.toml` and `pyproject.lock`.
I need to mention that unlike last time creating dependencies for `flake8-pep3101` and `pytest-flake8` ended with error. I don't know how critical it is. All others are OK.
I also removed setup.py and tox.ini in my PR.
And I didn't clearly understand your point 3, where you ask to add pyhon3.5 to the supported versions. Maybe you mean [this line](https://github.com/sobolevn/dump-env/blob/master/pyproject.toml#L41)?

Can we check that everything I made for points 1-4 is OK, before I start to refactor `travis.yml`?

_PS I'll try to make correct PR right after this comment._

**Comment by sobolevn** [comment]
> I need to mention that unlike last time creating dependencies for flake8-pep3101 and pytest-flake8 ended with error. I don't know how critical it is.

**Comment by tmsv** [comment]
> What kind of error did you encounter? It is not clear now.

**this for `flake8-pep3101:`**

poetry add --dev flake8-pep3101
Using version ^1.2 for flake8-pep3101

Updating dependencies
Resolving dependencies...

[SolverProblemError]
    Because no versions of flake8-pep3101 match >1.2,<1.2.1 || >1.2.1,<2.0
 and flake8-pep3101 (1.2) depends on flake8 (>=3.0), flake8-pep3101 (>=1.2,<1.2.1 || >1.2.1,<2.0) requires flake8 (>
=3.0).
(1) So, because flake8-pep3101 (1.2.1) depends on flake8 (>=3.0), flake8-pep3101 (>=1.2,<2.0) requires flake8 (>=3.0
).
    Because no versions of flake8 match >3.0,<3.0.1 || >3.0.1,<3.0.2.dev0 || >3.0.2.dev0,<3.0.2.dev1 || >3.0.2.dev1,
<3.0.2 || >3.0.2,<3.0.3 || >3.0.3,<3.0.4 || >3.0.4,<3.1.0 || >3.1.0,<3.1.1 || >3.1.1,<3.2.0 || >3.2.0,<3.2.1 || >3.2
.1,<3.3.0.dev0 || >3.3.0.dev0,<3.3.0 || >3.3.0,<3.4.0 || >3.4.0,<3.4.1 || >3.4.1,<3.5.0 || >3.5.0,<4.0.0
 and flake8 (3.0.2.dev0) depends on pycodestyle (>=2.0.0,<2.1.0), flake8 (>3.0,<3.0.1 || >3.0.1,<3.0.2.dev1 || >3.0.
2.dev1,<3.0.2 || >3.0.2,<3.0.3 || >3.0.3,<3.0.4 || >3.0.4,<3.1.0 || >3.1.0,<3.1.1 || >3.1.1,<3.2.0 || >3.2.0,<3.2.1
|| >3.2.1,<3.3.0.dev0 || >3.3.0.dev0,<3.3.0 || >3.3.0,<3.4.0 || >3.4.0,<3.4.1 || >3.4.1,<3.5.0 || >3.5.0,<4.0.0) req
uires pycodestyle (>=2.0.0,<2.1.0).
    And because flake8 (3.0.2.dev1) depends on pycodestyle (>=2.0.0,<2.1.0), flake8 (>3.0,<3.0.1 || >3.0.1,<3.0.2 ||
 >3.0.2,<3.0.3 || >3.0.3,<3.0.4 || >3.0.4,<3.1.0 || >3.1.0,<3.1.1 || >3.1.1,<3.2.0 || >3.2.0,<3.2.1 || >3.2.1,<3.3.0
.dev0 || >3.3.0.dev0,<3.3.0 || >3.3.0,<3.4.0 || >3.4.0,<3.4.1 || >3.4.1,<3.5.0 || >3.5.0,<4.0.0) requires pycodestyl
e (>=2.0.0,<2.1.0).
    And because flake8 (3.3.0.dev0) depends on pycodestyle (>=2.0.0,<2.3.0)
 and flake8 (3.0.0) depends on pycodestyle (>=2.0.0,<2.1.0), flake8 (>=3.0,<3.0.1 || >3.0.1,<3.0.2 || >3.0.2,<3.0.3
|| >3.0.3,<3.0.4 || >3.0.4,<3.1.0 || >3.1.0,<3.1.1 || >3.1.1,<3.2.0 || >3.2.0,<3.2.1 || >3.2.1,<3.3.0 || >3.3.0,<3.4
.0 || >3.4.0,<3.4.1 || >3.4.1,<3.5.0 || >3.5.0,<4.0.0) requires pycodestyle (>=2.0.0,<2.3.0).
    And because flake8 (3.0.1) depends on pycodestyle (>=2.0.0,<2.1.0)
 and flake8 (3.0.2) depends on pycodestyle (>=2.0.0,<2.1.0), flake8 (>=3.0,<3.0.3 || >3.0.3,<3.0.4 || >3.0.4,<3.1.0
|| >3.1.0,<3.1.1 || >3.1.1,<3.2.0 || >3.2.0,<3.2.1 || >3.2.1,<3.3.0 || >3.3.0,<3.4.0 || >3.4.0,<3.4.1 || >3.4.1,<3.5
.0 || >3.5.0,<4.0.0) requires pycodestyle (>=2.0.0,<2.3.0).
    And because flake8 (3.0.3) depends on pycodestyle (>=2.0.0,<2.1.0)
 and flake8 (3.0.4) depends on pycodestyle (>=2.0.0,<2.1.0), flake8 (>=3.0,<3.1.0 || >3.1.0,<3.1.1 || >3.1.1,<3.2.0
|| >3.2.0,<3.2.1 || >3.2.1,<3.3.0 || >3.3.0,<3.4.0 || >3.4.0,<3.4.1 || >3.4.1,<3.5.0 || >3.5.0,<4.0.0) requires pyco
destyle (>=2.0.0,<2.3.0).
    And because flake8 (3.1.0) depends on pycodestyle (>=2.0.0,<2.1.0)
 and flake8 (3.1.1) depends on pycodestyle (>=2.0.0,<2.2.0), flake8 (>=3.0,<3.2.0 || >3.2.0,<3.2.1 || >3.2.1,<3.3.0
|| >3.3.0,<3.4.0 || >3.4.0,<3.4.1 || >3.4.1,<3.5.0 || >3.5.0,<4.0.0) requires pycodestyle (>=2.0.0,<2.3.0).
    And because flake8 (3.2.0) depends on pycodestyle (>=2.0.0,<2.3.0)
 and flake8 (3.2.1) depends on pycodestyle (>=2.0.0,<2.3.0), flake8 (>=3.0,<3.3.0 || >3.3.0,<3.4.0 || >3.4.0,<3.4.1
|| >3.4.1,<3.5.0 || >3.5.0,<4.0.0) requires pycodestyle (>=2.0.0,<2.3.0).
    And because flake8 (3.3.0) depends on pycodestyle (>=2.0.0,<2.4.0)
 and flake8 (3.4.0) depends on pycodestyle (>=2.0.0,<2.4.0), flake8 (>=3.0,<3.4.1 || >3.4.1,<3.5.0 || >3.5.0,<4.0.0)
 requires pycodestyle (>=2.0.0,<2.4.0).
    And because flake8 (3.4.1) depends on pycodestyle (>=2.0.0,<2.4.0)
 and flake8 (3.5.0) depends on pycodestyle (>=2.0.0,<2.4.0), flake8 (>=3.0,<4.0.0) requires pycodestyle (>=2.0.0,<2.
4.0).
    And because flake8-pep3101 (>=1.2,<2.0) requires flake8 (>=3.0) (1), flake8-pep3101 (>=1.2,<2.0) requires pycode
style (>=2.0.0,<2.4.0) or flake8 (>=4.0.0)
    And because flake8-commas (2.0.0) depends on flake8 (>=2,<4.0.0), if flake8-pep3101 (>=1.2,<2.0) and flake8-comm
as (2.0.0) then pycodestyle (>=2.0.0,<2.4.0).
    And because no versions of flake8-commas match >2.0,<3.0
 and fornsobolev depends on pycodestyle (^2.4), flake8-pep3101 (>=1.2,<2.0) is incompatible with flake8-commas (>=2.
0,<3.0).
    So, because fornsobolev depends on both flake8-commas (^2.0) and flake8-pep3101 (^1.2), version solving failed.

add [-D|--dev] [--git GIT] [--path PATH] [-E|--extras EXTRAS] [--optional] [--python PYTHON] [--platform PLATFORM] [--allow-prereleases] [--dry-run] [--] <name> (<name>)...

**and this for `pytest-flake8`:**

poetry add --dev pytest-flake8
Using version ^1.0 for pytest-flake8

Updating dependencies
Resolving dependencies...

[SolverProblemError]
Because no versions of pytest-flake8 match >1.0,<1.0.1 || >1.0.1,<1.0.2 || >1.0.2,<2.0
 and pytest-flake8 (1.0.0) depends on flake8 (>=3.5), pytest-flake8 (>=1.0,<1.0.1 || >1.0.1,<1.0.2 || >1.0.2,<2.0) r
equires flake8 (>=3.5).
And because pytest-flake8 (1.0.1) depends on flake8 (>=3.5)
 and pytest-flake8 (1.0.2) depends on flake8 (>=3.5), pytest-flake8 (>=1.0,<2.0) requires flake8 (>=3.5).
Because flake8 (3.5.0) depends on pycodestyle (>=2.0.0,<2.4.0)
 and no versions of flake8 match >3.5,<4.0.0, flake8 (>=3.5,<4.0.0) requires pycodestyle (>=2.0.0,<2.4.0).
Thus, pytest-flake8 (>=1.0,<2.0) requires pycodestyle (>=2.0.0,<2.4.0) or flake8 (>=4.0.0).
And because flake8-commas (2.0.0) depends on flake8 (>=2,<4.0.0), if pytest-flake8 (>=1.0,<2.0) and flake8-commas (2
.0.0) then pycodestyle (>=2.0.0,<2.4.0).
And because no versions of flake8-commas match >2.0,<3.0
 and fornsobolev depends on pycodestyle (^2.4), pytest-flake8 (>=1.0,<2.0) is incompatible with flake8-commas (>=2.0
,<3.0).
So, because fornsobolev depends on both flake8-commas (^2.0) and pytest-flake8 (^1.0), version solving failed.

add [-D|--dev] [--git GIT] [--path PATH] [-E|--extras EXTRAS] [--optional] [--python PYTHON] [--platform PLATFORM] [--allow-prereleases] [--dry-run] [--] <name> (<name>)...


**So we can see that the first lines in each case gave us versions, updating and resolving but then smth went wrong.** 
**I'm sorry for the formatting going crazy due to <> symbols. Insert code option doesn't work normally too**

**Comment by AlwxSin** [comment]
Done in #10 #13 #15 #16
